[Tables]
[Tables.1]
TableName = "db*/runoob_tbl*" # database table支持前缀后缀通配符，Ex: *abc, abc*, *abc*, *
Measurement = "cndb/*" # database measurement含有星号时会使用mysql中数据库、表名值
SqlFields = [
                ["runoob_id","runoob_title","runoob_author","submission_date","ts"], # mysql字段名字，顺序要与mysqldump后字段值一致
                ["id","title","author","","ts"], # cnosdb字段名字,如果不需要存储空串替代
                [3,3,2,0,1],      # 1: 时间戳, 2: tag; 3: field
            ]
