name: Go

on:
  push:
    branches: [ test-workflows ]
  pull_request:
    branches: [ test-workflows ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      
    - name: Build
      run: go install ./...

    - name: Test
      run: go test ./...
      
    - name: Vet
      run: go vet ./...
    

      
